#ifndef OC_KYRSA_DYNAMIC_LIB_GLOBAL_H
#define OC_KYRSA_DYNAMIC_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OC_KYRSA_DYNAMIC_LIB_LIBRARY)
#  define OC_KYRSA_DYNAMIC_LIB_EXPORT Q_DECL_EXPORT
#else
#  define OC_KYRSA_DYNAMIC_LIB_EXPORT Q_DECL_IMPORT
#endif

#endif // OC_KYRSA_DYNAMIC_LIB_GLOBAL_H
